"""
Sample data used as a fallback when Mercado Libre's public API blocks
the /search and /items endpoints (HTTP 403).

Field structure mirrors the official documentation:
https://developers.mercadolivre.com.br/pt_br/itens-e-buscas

The dataset was deliberately built with variation to exercise the
downstream analytical queries in sql/ meaningfully:
  - sellers with multiple listings (e.g. 205417396, 118820033)
  - sellers with a single listing (e.g. 300998877, 301223344, ...)
  - both listings with and without warranty
  - a mix of shipping methods (fulfillment, drop_off, cross_docking)
  - a realistic price range in ARS
"""

SAMPLE_SEARCH_RESULTS = [
    # --- Seller 205417396 (TIENDA_SAMSUNG_OFICIAL) -> 5 listings ---
    {
        "id": "MLA1416598200",
        "sold_quantity": 342,
        "title": "Samsung Galaxy S24 128 Gb Cobalt Violet 8 Gb Ram",
        "condition": "new",
        "price": 899999.0,
        "currency_id": "ARS",
        "seller": {"id": 205417396, "nickname": "TIENDA_SAMSUNG_OFICIAL"},
        "shipping": {"free_shipping": True, "logistic_type": "fulfillment"},
        "warranty": "12 meses de garantía de fábrica",
    },
    {
        "id": "MLA1416598201",
        "sold_quantity": 128,
        "title": "Samsung Galaxy S24 Ultra 256 Gb Titanium Gray",
        "condition": "new",
        "price": 1299999.0,
        "currency_id": "ARS",
        "seller": {"id": 205417396, "nickname": "TIENDA_SAMSUNG_OFICIAL"},
        "shipping": {"free_shipping": True, "logistic_type": "fulfillment"},
        "warranty": "12 meses de garantía de fábrica",
    },
    {
        "id": "MLA1416598202",
        "sold_quantity": 76,
        "title": "Samsung Galaxy S24 Ultra 512 Gb Titanium Black",
        "condition": "new",
        "price": 1449999.0,
        "currency_id": "ARS",
        "seller": {"id": 205417396, "nickname": "TIENDA_SAMSUNG_OFICIAL"},
        "shipping": {"free_shipping": True, "logistic_type": "fulfillment"},
        "warranty": "12 meses de garantía de fábrica",
    },
    {
        "id": "MLA1416598203",
        "sold_quantity": 210,
        "title": "Samsung Galaxy S24 256 Gb Amber Yellow",
        "condition": "new",
        "price": 969999.0,
        "currency_id": "ARS",
        "seller": {"id": 205417396, "nickname": "TIENDA_SAMSUNG_OFICIAL"},
        "shipping": {"free_shipping": True, "logistic_type": "fulfillment"},
        "warranty": "12 meses de garantía de fábrica",
    },
    {
        "id": "MLA1416598204",
        "sold_quantity": 95,
        "title": "Samsung Galaxy S24+ 256 Gb Marble Gray",
        "condition": "new",
        "price": 1099999.0,
        "currency_id": "ARS",
        "seller": {"id": 205417396, "nickname": "TIENDA_SAMSUNG_OFICIAL"},
        "shipping": {"free_shipping": True, "logistic_type": "fulfillment"},
        "warranty": "12 meses de garantía de fábrica",
    },

    # --- Seller 118820033 (MOVISTAR_TIENDA_OFICIAL) -> 3 listings ---
    {
        "id": "MLA1420112233",
        "sold_quantity": 189,
        "title": "Samsung Galaxy S24 FE 256gb Blue",
        "condition": "new",
        "price": 749999.0,
        "currency_id": "ARS",
        "seller": {"id": 118820033, "nickname": "MOVISTAR_TIENDA_OFICIAL"},
        "shipping": {"free_shipping": True, "logistic_type": "drop_off"},
        "warranty": "Sin garantía",
    },
    {
        "id": "MLA1420112234",
        "sold_quantity": 156,
        "title": "Samsung Galaxy S24 FE 128gb Graphite",
        "condition": "new",
        "price": 699999.0,
        "currency_id": "ARS",
        "seller": {"id": 118820033, "nickname": "MOVISTAR_TIENDA_OFICIAL"},
        "shipping": {"free_shipping": False, "logistic_type": "drop_off"},
        "warranty": "Sin garantía",
    },
    {
        "id": "MLA1420112235",
        "sold_quantity": 47,
        "title": "Samsung Galaxy S24 Plus 512gb Cobalt Violet",
        "condition": "new",
        "price": 1189999.0,
        "currency_id": "ARS",
        "seller": {"id": 118820033, "nickname": "MOVISTAR_TIENDA_OFICIAL"},
        "shipping": {"free_shipping": True, "logistic_type": "cross_docking"},
        "warranty": "6 meses de garantía del vendedor",
    },

    # --- Seller 300112244 (CELULARES_DEL_SUR) -> 2 listings ---
    {
        "id": "MLA1430556677",
        "sold_quantity": 63,
        "title": "Samsung Galaxy S24 Ultra 256gb Gris Titanio Global",
        "condition": "new",
        "price": 1259999.0,
        "currency_id": "ARS",
        "seller": {"id": 300112244, "nickname": "CELULARES_DEL_SUR"},
        "shipping": {"free_shipping": True, "logistic_type": "fulfillment"},
        "warranty": "12 meses de garantía de fábrica",
    },
    {
        "id": "MLA1430556678",
        "sold_quantity": 118,
        "title": "Samsung Galaxy S24 128gb Violeta Global",
        "condition": "new",
        "price": 879999.0,
        "currency_id": "ARS",
        "seller": {"id": 300112244, "nickname": "CELULARES_DEL_SUR"},
        "shipping": {"free_shipping": False, "logistic_type": "drop_off"},
        "warranty": "3 meses de garantía del vendedor",
    },

    # --- Sellers with a single listing ---
    {
        "id": "MLA1440887701",
        "sold_quantity": 12,
        "title": "Samsung Galaxy S24 Ultra 1tb Titanium Violet Nuevo Sellado",
        "condition": "new",
        "price": 1699999.0,
        "currency_id": "ARS",
        "seller": {"id": 300998877, "nickname": "IMPORT_PHONES_AR"},
        "shipping": {"free_shipping": True, "logistic_type": "cross_docking"},
        "warranty": "Sin garantía",
    },
    {
        "id": "MLA1440887702",
        "sold_quantity": 88,
        "title": "Samsung Galaxy S24 5g 256gb Doble Sim Global Version",
        "condition": "new",
        "price": 949999.0,
        "currency_id": "ARS",
        "seller": {"id": 301223344, "nickname": "TECNO_STORE_BSAS"},
        "shipping": {"free_shipping": True, "logistic_type": "fulfillment"},
        "warranty": "12 meses de garantía de fábrica",
    },
    {
        "id": "MLA1440887703",
        "sold_quantity": 134,
        "title": "Samsung Galaxy S24 Fe 5g 128gb Mint",
        "condition": "new",
        "price": 679999.0,
        "currency_id": "ARS",
        "seller": {"id": 301556677, "nickname": "MUNDO_CELULAR_ROSARIO"},
        "shipping": {"free_shipping": False, "logistic_type": "drop_off"},
        "warranty": "6 meses de garantía del vendedor",
    },
    {
        "id": "MLA1440887704",
        "sold_quantity": 29,
        "title": "Samsung Galaxy S24 Ultra 256gb Yellow Titanium Edicion Especial",
        "condition": "new",
        "price": 1379999.0,
        "currency_id": "ARS",
        "seller": {"id": 301889900, "nickname": "PREMIUM_MOBILE_CBA"},
        "shipping": {"free_shipping": True, "logistic_type": "fulfillment"},
        "warranty": "12 meses de garantía de fábrica",
    },
    {
        "id": "MLA1440887705",
        "sold_quantity": 71,
        "title": "Samsung Galaxy S24 Plus 256gb Marble Gray Liberado",
        "condition": "new",
        "price": 1059999.0,
        "currency_id": "ARS",
        "seller": {"id": 302001122, "nickname": "OFERTAS_TECH_MENDOZA"},
        "shipping": {"free_shipping": True, "logistic_type": "drop_off"},
        "warranty": "Sin garantía",
    },
    {
        "id": "MLA1440887706",
        "sold_quantity": 156,
        "title": "Samsung Galaxy S24 128gb Onyx Black Dual Sim",
        "condition": "new",
        "price": 869999.0,
        "currency_id": "ARS",
        "seller": {"id": 302334455, "nickname": "ARGENCEL_STORE"},
        "shipping": {"free_shipping": False, "logistic_type": "cross_docking"},
        "warranty": "3 meses de garantía del vendedor",
    },
    {
        "id": "MLA1440887707",
        "sold_quantity": 18,
        "title": "Samsung Galaxy S24 Ultra 512gb Titanium Gray Version Snapdragon",
        "condition": "new",
        "price": 1489999.0,
        "currency_id": "ARS",
        "seller": {"id": 302667788, "nickname": "SMARTPHONES_PATAGONIA"},
        "shipping": {"free_shipping": True, "logistic_type": "fulfillment"},
        "warranty": "12 meses de garantía de fábrica",
    },
    {
        "id": "MLA1440887708",
        "sold_quantity": 203,
        "title": "Samsung Galaxy S24 Fe 256gb Graphite Nuevo",
        "condition": "new",
        "price": 739999.0,
        "currency_id": "ARS",
        "seller": {"id": 302990011, "nickname": "CELUMANIA_TUCUMAN"},
        "shipping": {"free_shipping": True, "logistic_type": "drop_off"},
        "warranty": "6 meses de garantía del vendedor",
    },
    {
        "id": "MLA1440887709",
        "sold_quantity": 54,
        "title": "Samsung Galaxy S24 Plus 512gb Cobalt Violet Global",
        "condition": "new",
        "price": 1229999.0,
        "currency_id": "ARS",
        "seller": {"id": 303112233, "nickname": "NORTE_CELULARES"},
        "shipping": {"free_shipping": False, "logistic_type": "drop_off"},
        "warranty": "Sin garantía",
    },
    {
        "id": "MLA1440887710",
        "sold_quantity": 33,
        "title": "Samsung Galaxy S24 Ultra 256gb Titanium Violet Ed. Limitada",
        "condition": "new",
        "price": 1319999.0,
        "currency_id": "ARS",
        "seller": {"id": 303445566, "nickname": "GALAXY_HOUSE_CORDOBA"},
        "shipping": {"free_shipping": True, "logistic_type": "cross_docking"},
        "warranty": "12 meses de garantía de fábrica",
    },
    {
        "id": "MLA1440887711",
        "sold_quantity": 167,
        "title": "Samsung Galaxy S24 128gb Cobalt Violet Dual Chip",
        "condition": "new",
        "price": 859999.0,
        "currency_id": "ARS",
        "seller": {"id": 303778899, "nickname": "FULL_PHONE_SALTA"},
        "shipping": {"free_shipping": True, "logistic_type": "fulfillment"},
        "warranty": "12 meses de garantía de fábrica",
    },
]

# Reference exchange rate used only when the live /currency_conversions
# call is unavailable (see extract.py).
SAMPLE_CURRENCY_CONVERSION = {
    "from": "ARS",
    "to": "USD",
    "ratio": 0.00098,
}